.TH "headers/GlobalVariables.h" 3 "Tue May 14 2019" "Space Race" \" -*- nroff -*-
.ad l
.nh
.SH NAME
headers/GlobalVariables.h
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSCREEN_WIDTH\fP   1280"
.br
.ti -1c
.RI "#define \fBSCREEN_HEIGHT\fP   720"
.br
.ti -1c
.RI "#define \fBGAME_BACKGROUND_FILEPATH\fP   'Resources/textures/space\&.png'"
.br
.ti -1c
.RI "#define \fBPLAY_BUTTON_FILEPATH\fP   'Resources/textures/PlayButton\&.png'"
.br
.ti -1c
.RI "#define \fBASTEROID_1_FILEPATH\fP   'Resources/textures/asteroid_1\&.png'"
.br
.ti -1c
.RI "#define \fBCOIN_FILEPATH\fP   'Resources/textures/coin\&.png'"
.br
.ti -1c
.RI "#define \fBSPACESHIP_FILEPATH\fP   'Resources/textures/spaceship\&.png'"
.br
.ti -1c
.RI "#define \fBSCORE_FONT_FILEPATH\fP   'Resources/fonts/promethean\&.ttf'"
.br
.ti -1c
.RI "#define \fBITEM_MOVEMENT_SPEED\fP   200\&.0f"
.br
.ti -1c
.RI "#define \fBITEM_SPAWN_FREQUENCY\fP   1\&.0f"
.br
.ti -1c
.RI "#define \fBSPACESHIP_FLYING_SPEED\fP   350\&.0f"
.br
.ti -1c
.RI "#define \fBSPACESHIP_ROTATION_SPEED\fP   100\&.0f"
.br
.ti -1c
.RI "#define \fBTIME_BEFORE_GAME_OVER_APPEARS\fP   1\&.5f"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define ASTEROID_1_FILEPATH   'Resources/textures/asteroid_1\&.png'"

.PP
Definition at line 14 of file GlobalVariables\&.h\&.
.SS "#define COIN_FILEPATH   'Resources/textures/coin\&.png'"

.PP
Definition at line 15 of file GlobalVariables\&.h\&.
.SS "#define GAME_BACKGROUND_FILEPATH   'Resources/textures/space\&.png'"

.PP
Definition at line 10 of file GlobalVariables\&.h\&.
.SS "#define ITEM_MOVEMENT_SPEED   200\&.0f"

.PP
Definition at line 20 of file GlobalVariables\&.h\&.
.SS "#define ITEM_SPAWN_FREQUENCY   1\&.0f"

.PP
Definition at line 21 of file GlobalVariables\&.h\&.
.SS "#define PLAY_BUTTON_FILEPATH   'Resources/textures/PlayButton\&.png'"

.PP
Definition at line 12 of file GlobalVariables\&.h\&.
.SS "#define SCORE_FONT_FILEPATH   'Resources/fonts/promethean\&.ttf'"

.PP
Definition at line 18 of file GlobalVariables\&.h\&.
.SS "#define SCREEN_HEIGHT   720"

.PP
Definition at line 8 of file GlobalVariables\&.h\&.
.SS "#define SCREEN_WIDTH   1280"
Defining varialbes that are used throught the whole program 
.PP
Definition at line 7 of file GlobalVariables\&.h\&.
.SS "#define SPACESHIP_FILEPATH   'Resources/textures/spaceship\&.png'"

.PP
Definition at line 16 of file GlobalVariables\&.h\&.
.SS "#define SPACESHIP_FLYING_SPEED   350\&.0f"

.PP
Definition at line 23 of file GlobalVariables\&.h\&.
.SS "#define SPACESHIP_ROTATION_SPEED   100\&.0f"

.PP
Definition at line 25 of file GlobalVariables\&.h\&.
.SS "#define TIME_BEFORE_GAME_OVER_APPEARS   1\&.5f"

.PP
Definition at line 27 of file GlobalVariables\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Space Race from the source code\&.
