CC = g++
CFLAGS = -g -Wall

Lecture14: RemoveStd PureVirtual VirtualDestructor

RemoveStd: RemoveStd.cpp
	${CC} ${CFLAGS} RemoveStd.cpp -o RemoveStd

PureVirtual: PureVirtual.cpp
	${CC} ${CFLAGS} PureVirtual.cpp -o PureVirtual

VirtualDestructor: VirtualDestructor.cpp
	${CC} ${CFLAGS} VirtualDestructor.cpp -o VirtualDestructor

clean: 
	rm RemoveStd PureVirtual VirtualDestructor
